import "./globals.css";
import { Ubuntu } from "next/font/google";

import type { FC, PropsWithChildren } from "react";
import Header from "@/components/Layout/Header";
import Footer from "@/components/Layout/Footer";

const inter = Ubuntu({ weight: "300", subsets: ["latin"] });

export const metadata = {
  title: "Next.js Static CMS Blog",
  description: "Next.js blog template for Static CMS on Netlify",
};

const RootLayout: FC<PropsWithChildren> = ({ children }) => {
  return (
  <html lang="en">
    <head>
      <title>Create Wix Education Site</title>
      <meta
          name="description"
          content="Generated by create next app with Wix Education integration"
      />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="https://www.wix.com/favicon.ico" />
    </head>
    <body className="text-blue-site bg-white">
          <Header />
          <main className="bg-white min-h-[600px]">{children}</main>
          <div className="mt-10 sm:mt-20">
            <Footer />
          </div>
    </body>
  </html>
  );
};

export default RootLayout;
